# 路由HTTP服务配置
route:
  - addr: "0.0.0.0:29565"
    schema: http

# NE 网元信息
ne:
  type: "OAM" # 类型
  version: "" # 版本号
  serialNum: "" # 序列号
  expiryDate: "2000-01-01" # 过期时间
  nbNumber: 0 # 基站限制数量
  ueNumber: 0 # 终端限制数量
  pid: 0 # 进程ID

# OMC 网管信息
omc:
  url: "" # 网管目标地址
  coreUID: "" # 网管上核心网唯一标识
  neUID: "" # 网管上网元唯一标识
  kpiGranularity: 0 # KPI 指标推送周期(单位秒), 0 表示不开启定时推送

# 文件上传
upload:
  fileDir: "/usr/local/oam/upload"
  # 最大上传文件大小，默认为 10mb
  fileSize: 10
  # 文件扩展名白名单
  whiteList:
    # 图片
    - ".bmp"
    - ".webp"
    - ".gif"
    - ".jpg"
    - ".jpeg"
    - ".png"
    # word excel powerpoint
    - ".doc"
    - ".docx"
    - ".xls"
    - ".xlsx"
    - ".ppt"
    - ".pptx"
    # 文本文件
    - ".html"
    - ".htm"
    - ".txt"
    # pdf
    - ".pdf"
    # 压缩文件
    - ".zip"
    - ".gz"
    - ".tgz"
    - ".gzip"
    # 音视频格式
    - ".mp3"
    - ".mp4"
    - ".avi"
    - ".rmvb"
    # 软件包
    - ".deb"
    - ".rpm"
    # 验证文件
    - ".ini"
